# Generated by Django 4.1.1 on 2022-09-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=280)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('author_id', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
